# Generated by Django 4.1.5 on 2023-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuobject_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuobject',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
